/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as authAuthRegisterRouteImport } from './routes/(auth)/auth/register'
import { Route as authAuthLayoutRouteImport } from './routes/(auth)/auth/_layout'
import { Route as authAuthLoginIndexRouteImport } from './routes/(auth)/auth/login.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/(auth)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutRoute = authAuthLayoutRouteImport.update({
  id: '/(auth)/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginIndexRoute = authAuthLoginIndexRouteImport.update({
  id: '/(auth)/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof authAuthLayoutRoute
  '/auth/register': typeof authAuthRegisterRoute
  '/auth/login': typeof authAuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof authAuthLayoutRoute
  '/auth/register': typeof authAuthRegisterRoute
  '/auth/login': typeof authAuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_layout': typeof appLayoutRoute
  '/(auth)/auth/_layout': typeof authAuthLayoutRoute
  '/(auth)/auth/register': typeof authAuthRegisterRoute
  '/(auth)/auth/login/': typeof authAuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/auth/register' | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/auth/register' | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/(app)/_layout'
    | '/(auth)/auth/_layout'
    | '/(auth)/auth/register'
    | '/(auth)/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appLayoutRoute: typeof appLayoutRoute
  authAuthLayoutRoute: typeof authAuthLayoutRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
  authAuthLoginIndexRoute: typeof authAuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/register': {
      id: '/(auth)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/_layout': {
      id: '/(auth)/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login/': {
      id: '/(auth)/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appLayoutRoute: appLayoutRoute,
  authAuthLayoutRoute: authAuthLayoutRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
  authAuthLoginIndexRoute: authAuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
